server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: simple
    password: simple
  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: home
        jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: true
    default-schema: home
    user: simple
    password: simple
    change-log: classpath:/db/changelog/changelog_master.xml